### ISSUE TITLE
Tasks and ideas

### ISSUE THREAD

**Issue by MatheusCavalca** [MatheusCavalca/Knock#1]
Hey @lfarah, as soon as I've set you as a collaborator, I would be very happy if you could give me your opinion about some topics:
- **Customizable options:**
  - [x] Number of "knocks" to trigger event.
  - [x] Minimum and maximum time interval allowed between "knocks" to trigger a single event.
  - [x] Time interval allowed between "knock events".
  - [x] "Z" variation needed to recognize a knock (Considering cartesian coordinates (X, Y and Z ) and accelerometer data, the Z variation is related to the oscillation of the phone when the user "knocks" it).
- **General ideas and tasks:**
  - [x] Create lincese and the CocoaPod. 
  - [x] Use the existent app as an example of the library when it's finished and the pod is created.
  - [x] Change name from "Knock-to-React" to KnockToReact
  - [x] Add Gif showing how it works

Please, feel free to give me your ideas about the list above and about every other topic. And again, thank you for helping me with this small project (it is really important to me). :smile:

**Comment by lfarah** [comment]
Hey, let's create several issues for each one of this tasks

**Comment by MatheusCavalca** [comment]
Great, thanks for that. I'll start by creating a new Swift project (the project was built using Objective-C) and adding it to the repo. I believe I will have time to work on it this week, so every task that I start I update the issue.

**Comment by lfarah** [comment]
Closing this because all the tasks here moved to different issues
