### ISSUE TITLE
Customization

### ISSUE THREAD

**Issue by lfarah** [MatheusCavalca/Knock#6]
- Number of "knocks" to trigger event.
- Minimum and maximum time interval allowed between "knocks" to trigger a single event.
- Time interval allowed between "knock events".
- "Z" variation needed to recognize a knock (Considering cartesian coordinates (X, Y and Z ) and accelerometer data, the Z variation is related to the oscillation of the phone when the user "knocks" it).

We'll have to create separate issues later, but for right now, let's keep them organized here

**Comment by lfarah** [comment]
> public properties for customization

**Comment by MatheusCavalca** [comment]
Done with the properties below:
- limitDifference
- numberOfKnocksNeeded
- minimumTimeBetweenSingleKnocks
- maximumTimeBetweenSingleKnocks
- timeNeededBetweenKnockOperations
