### ISSUE TITLE
KnockToReact.swift not working

### ISSUE THREAD

**Issue by lfarah** [MatheusCavalca/Knock#7]
I don't know why it won't work. I copied line by line :cry:

**Comment by MatheusCavalca** [comment]
hey @lfarah, I've made some changes on the original implementation in Swift, now it is working properly and in foreground. The class `KnockToReact.swift` is already using a customisable implementation, so we just need to make some adjusts and it will be good to go. Please, take a look at my last commit and give me your opinion.

Also, I've thought about a general structure of the project:
- Example App:
  - [x] Only in Swift.
  - [ ] Uses the `KnockToReact.swift` in a background task (very similar to the original Obj-c example app, but with background tasks being handled in the example app and not in the main lib class).
  - [x] Not use the class SingletonLocation anymore (trigger notification with message "knock performed").
  - [x] Form fields to give to user the option to customize values.
- Library:
  - [x] Swift and Obj-c to drag and drop installation.
  - [x] Delegate to knockOperationPerformed.
  - [x] public properties for customization (do you think we should use data source instead?).

**Comment by lfarah** [comment]
Do we have to request anything to to the background task, or the devs may have their apps rejected on App Store?

**Comment by lfarah** [comment]
Datasource is too complicated. We could do something like:

``` swift
knockManager.numberOfKnocks = 2
knockManager.limitDifference *= 2
```

What do you think?

**Comment by lfarah** [comment]
BTW: can we implement the incrementLimitDifference again?

**Comment by lfarah** [comment]
I created different issues for what you said in the project structure. We only need to finish discussing the background tasks before we can close this _Bug_ issue

**Comment by MatheusCavalca** [comment]
- About the background task, as soon as we are going to implement it just in the example app, we don't have to worry about App Store release (it will not be in the lib), right? We can say that the example app uses background tasks that is not guaranteed to be approved by App Store review teams.
- So let's use public properties, did you see that I've changed some properties names? I believe that it is better now.
- Sure, we can implement the increment/decrement LimitDifference again, but the property `limitDifference` is called ZVariationThreshold now.

**Comment by lfarah** [comment]
The problem is that we're offering a feature that they'll never be able to use.
Also, I think that `limitDifference` is a simpler name to understand than _ZVariationThreshold_.

You definitely made a good job on rewriting the library and it's way cleaner now! :wink:

**Comment by MatheusCavalca** [comment]
Hm, I understand, actually I believe that an app that just uses background task with accelerometer isn't rejected on App Store. The problem is when using other background modes (like location). If you prefer, we can remove the background feature on the example app (even not being used in the lib). What do you think?

And about the `limitDifference` property, I am not sure if it is the best name yet, but we can use it for now (instead of `ZVariationThreshold`)

Thank you! :smile:

**Comment by MatheusCavalca** [comment]
Already changed `ZVariationThreshold` to `limitDifference` and included `incrementLimitDifference` and `decrementLimitDifference`.

**Comment by lfarah** [comment]
Take a look at [Knock to Unlock](http://www.knocktounlock.com). They are using the accelerometer in background and I think they are using that location in background to bypass something. I don't think that App Store people would approve this.
I'm talking about that because I once got rejected because of background location stuff and it sucks!
![img_0088](https://cloud.githubusercontent.com/assets/6511079/14055508/6cf1fdc6-f2c1-11e5-8f5e-4c6987edc873.PNG)

**Comment by MatheusCavalca** [comment]
Yes, I see. I had an app rejected because of the same thing, and it really sucks. So, do you think that just using background tasks would result in a rejected app? And how do you think that `KnockToUnlock` wasn't rejected?

(Maybe `KnockToUnlock` was accepted before the iOS 8 launch, when Apple started to reject more apps because of location permissions?)
